#!/usr/bin/env node

/**
 * Builds the browser catalog from data/catalog.json.
 *
 * The generated src/catalog/catalog.mjs is a browser asset; catalog.json is the source of
 * truth and should be edited instead of the generated file.
 */
const { existsSync, mkdirSync, readFileSync, writeFileSync } = require("node:fs");
const { join, resolve } = require("node:path");

const ROOT_DIR = resolve(__dirname, "..");
const DATA_DIR = resolve(ROOT_DIR, "data");
const SOURCE_PATH = join(DATA_DIR, "catalog.json");
const OUTPUT_PATH = join(ROOT_DIR, "src/catalog/catalog.mjs");
const INITIAL_OUTPUT_PATH = join(ROOT_DIR, "src/catalog/catalog-initial.mjs");
// Cities shipped with the first paint. The full catalog is fetched after LCP.
// Keep it small: Sao Paulo (hero poster city) is first in data/catalog.json.
const INITIAL_CITY_COUNT = 12;
const RADIO_INDEX_OUTPUT_PATH = join(ROOT_DIR, "src/radio/radio-catalog-index.mjs");
const MODES = ["drive", "bike", "walk", "drone", "beach_walk"];

function loadSourceCatalog() {
  if (!existsSync(SOURCE_PATH)) throw new Error(`Missing ${SOURCE_PATH}`);
  const catalog = JSON.parse(readFileSync(SOURCE_PATH, "utf8"));
  if (!Array.isArray(catalog)) throw new Error("data/catalog.json must contain an array");
  return catalog;
}

function normalizeCatalog(catalog) {
  // Strip per-video youtubeMeta (embedWidth/embedHeight/definition/dimension):
  // it only feeds the metadata sync pipeline (data/catalog.json keeps it) and
  // aspectRatio is the single field the player reads at runtime. This removes
  // ~40% of the browser bundle.
  const stripVideo = (video) => {
    if (!video || typeof video !== "object") return { ...video };
    const { youtubeMeta: _dropped, ...rest } = video;
    return { ...rest };
  };
  return catalog.map((city) => ({
    ...city,
    videos: Object.fromEntries(MODES.map((mode) => [
      mode,
      Array.isArray(city.videos?.[mode]) ? city.videos[mode].map(stripVideo) : []
    ])),
    radios: Array.isArray(city.radios) ? city.radios.slice(0, 5).map((radio) => ({ ...radio })) : []
  }));
}

function validateCatalog(catalog) {
  const cityKeys = new Set();
  const videoIds = new Set();
  for (const city of catalog) {
    if (!city?.name || !city?.country) throw new Error("Every catalog city needs name and country");
    const cityKey = `${city.name}\u0000${city.country}`;
    if (cityKeys.has(cityKey)) throw new Error(`Duplicate city: ${city.name}, ${city.country}`);
    cityKeys.add(cityKey);
    for (const mode of MODES) {
      for (const video of city.videos[mode]) {
        if (!/^[A-Za-z0-9_-]{11}$/.test(video.id || "")) throw new Error(`Invalid YouTube ID in ${city.name}: ${video.id}`);
        if (videoIds.has(video.id)) throw new Error(`Duplicate video ID: ${video.id}`);
        videoIds.add(video.id);
        if (!Number.isFinite(Number(video.start)) || Number(video.start) < 0) {
          throw new Error(`Invalid start time for ${video.id}`);
        }
      }
    }
    if (city.radios.length > 5) throw new Error(`Too many radios in ${city.name}; maximum is five`);
    for (const radio of city.radios) {
      if (!radio?.name || !/^https?:\/\//i.test(radio.url || "")) {
        throw new Error(`Invalid radio in ${city.name}`);
      }
    }
  }
}

function writeBrowserAsset(catalog) {
  const header = "// Generated from data/catalog.json. Do not edit this file directly.\n";
  writeFileSync(OUTPUT_PATH, `${header}const CATALOG = ${JSON.stringify(catalog)};\nexport { CATALOG };\nexport default CATALOG;\n`);
}

function writeInitialAsset(catalog) {
  const header = "// Generated from data/catalog.json. Do not edit this file directly.\n// Minimal first-paint catalog: the full list loads after LCP (see bootstrap.mjs).\n";
  const initial = catalog.slice(0, INITIAL_CITY_COUNT);
  writeFileSync(INITIAL_OUTPUT_PATH, `${header}const INITIAL_CATALOG = ${JSON.stringify(initial)};\nexport { INITIAL_CATALOG };\nexport default INITIAL_CATALOG;\n`);
  return initial.length;
}

function slugify(value) {
  return String(value || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function writeRadioIndex(catalog) {
  const radioCatalog = Object.fromEntries(catalog.map((city) => {
    const cityId = slugify(city.name);
    return [cityId, city.radios.map((radio, index) => ({
      stationRef: `catalog:${cityId}:${index}`,
      name: String(radio.name || "").trim(),
      url: String(radio.url || "").trim()
    }))];
  }));
  const header = "// Generated from data/catalog.json. Do not edit this file directly.\n";
  const source = `${header}const RADIO_CATALOG = ${JSON.stringify(radioCatalog)};\n\nexport function findCatalogStation(stationRef) {\n  const match = String(stationRef || \"\").match(/^catalog:([^:]+):(\\d+)$/);\n  if (!match) return null;\n  const station = RADIO_CATALOG[match[1]]?.[Number(match[2])];\n  return station ? { ...station } : null;\n}\n\nexport { RADIO_CATALOG };\nexport default RADIO_CATALOG;\n`;
  writeFileSync(RADIO_INDEX_OUTPUT_PATH, source);
}

function main() {
  mkdirSync(DATA_DIR, { recursive: true });
  mkdirSync(resolve(ROOT_DIR, "src/catalog"), { recursive: true });
  const catalog = normalizeCatalog(loadSourceCatalog());
  validateCatalog(catalog);
  writeBrowserAsset(catalog);
  const initialCount = writeInitialAsset(catalog);
  mkdirSync(resolve(ROOT_DIR, "src/radio"), { recursive: true });
  writeRadioIndex(catalog);
  console.log(`Catalog built: ${catalog.length} cities (${initialCount} initial), ${catalog.reduce((total, city) => total + Object.values(city.videos).reduce((count, videos) => count + videos.length, 0), 0)} videos, ${catalog.reduce((total, city) => total + city.radios.length, 0)} radios.`);
}

main();
