#!/usr/bin/env node

/**
 * Builds the browser catalog from data/catalog.json.
 *
 * The generated src/catalog/catalog.mjs is a browser asset; catalog.json is the source of
 * truth and should be edited instead of the generated file.
 */
const { existsSync, mkdirSync, readFileSync, writeFileSync } = require("node:fs");
const { join, resolve } = require("node:path");

const ROOT_DIR = resolve(__dirname, "..");
const DATA_DIR = resolve(ROOT_DIR, "data");
const SOURCE_PATH = join(DATA_DIR, "catalog.json");
const OUTPUT_PATH = join(ROOT_DIR, "src/catalog/catalog.mjs");
const MODES = ["drive", "bike", "walk", "drone", "beach_walk"];

function loadSourceCatalog() {
  if (!existsSync(SOURCE_PATH)) throw new Error(`Missing ${SOURCE_PATH}`);
  const catalog = JSON.parse(readFileSync(SOURCE_PATH, "utf8"));
  if (!Array.isArray(catalog)) throw new Error("data/catalog.json must contain an array");
  return catalog;
}

function normalizeCatalog(catalog) {
  return catalog.map((city) => ({
    ...city,
    videos: Object.fromEntries(MODES.map((mode) => [
      mode,
      Array.isArray(city.videos?.[mode]) ? city.videos[mode].map((video) => ({ ...video })) : []
    ])),
    radios: Array.isArray(city.radios) ? city.radios.slice(0, 5).map((radio) => ({ ...radio })) : []
  }));
}

function validateCatalog(catalog) {
  const cityKeys = new Set();
  const videoIds = new Set();
  for (const city of catalog) {
    if (!city?.name || !city?.country) throw new Error("Every catalog city needs name and country");
    const cityKey = `${city.name}\u0000${city.country}`;
    if (cityKeys.has(cityKey)) throw new Error(`Duplicate city: ${city.name}, ${city.country}`);
    cityKeys.add(cityKey);
    for (const mode of MODES) {
      for (const video of city.videos[mode]) {
        if (!/^[A-Za-z0-9_-]{11}$/.test(video.id || "")) throw new Error(`Invalid YouTube ID in ${city.name}: ${video.id}`);
        if (videoIds.has(video.id)) throw new Error(`Duplicate video ID: ${video.id}`);
        videoIds.add(video.id);
        if (!Number.isFinite(Number(video.start)) || Number(video.start) < 0) {
          throw new Error(`Invalid start time for ${video.id}`);
        }
      }
    }
    if (city.radios.length > 5) throw new Error(`Too many radios in ${city.name}; maximum is five`);
    for (const radio of city.radios) {
      if (!radio?.name || !/^https?:\/\//i.test(radio.url || "")) {
        throw new Error(`Invalid radio in ${city.name}`);
      }
    }
  }
}

function writeBrowserAsset(catalog) {
  const header = "// Generated from data/catalog.json. Do not edit this file directly.\n";
  writeFileSync(OUTPUT_PATH, `${header}const CATALOG = ${JSON.stringify(catalog)};\nexport { CATALOG };\nexport default CATALOG;\n`);
}

function main() {
  mkdirSync(DATA_DIR, { recursive: true });
  mkdirSync(resolve(ROOT_DIR, "src/catalog"), { recursive: true });
  const catalog = normalizeCatalog(loadSourceCatalog());
  validateCatalog(catalog);
  writeBrowserAsset(catalog);
  console.log(`Catalog built: ${catalog.length} cities, ${catalog.reduce((total, city) => total + Object.values(city.videos).reduce((count, videos) => count + videos.length, 0), 0)} videos, ${catalog.reduce((total, city) => total + city.radios.length, 0)} radios.`);
}

main();
